apps/cmp/urls.py
from django.urls import include, path
from .views import ProveedorView, ProveedorNew, ProveedorEdit, ProveedorInactivar,\
    ComprasView, compras, CompraDetDelete

from .reportes import reporte_compras, imprimir_compra

urlpatterns = [
    path(r'proveedores/', ProveedorView.as_view(), name='proveedor_list'),
    path(r'proveedores/new', ProveedorNew.as_view(), name='proveedor_new'),
    path(r'proveedores/edit/<int:pk>', ProveedorEdit.as_view(), name='proveedor_edit'),
    path(r'proveedores/inactivar/<int:id>', ProveedorInactivar, name='proveedor_inactivar'),
    
    path(r'compras/', ComprasView.as_view(), name='compras_list'),
    path(r'compras/new', compras, name='compras_new'),
    path(r'compras/edit/<int:compra_id>', compras, name='compras_edit'),
    path(r'compras/<int:compra_id>/delete/<int:pk>', CompraDetDelete.as_view(), name='compras_del'),
    
    path(r'compras/listado', reporte_compras, name='compras_print_all'),
    path(r'compras/<int:compra_id>/imprimir', imprimir_compra, name='compras_print_one'),
    
]

apps/inv/urls.py
from django.urls import include, path
from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel,\
    SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, \
        MarcaView, MarcaNew, MarcaEdit, marca_inactivar, \
        UnidadMedidaView, UnidadMedidaNew,  UnidadMedidaEdit, unidadmedida_inactivar, \
            ProductoView,  ProductoNew, ProductoEdit, Producto_inactivar
        # MarcaDel


urlpatterns = [
    # path('admin/', admin.site.urls),
    path(r'categorias/', CategoriaView.as_view(), name='categoria_list'),
    path(r'categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path(r'categorias/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path(r'categorias/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_del'),
    
    path(r'subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path(r'subcategorias/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path(r'subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path(r'subcategorias/delete/<int:pk>', SubCategoriaDel.as_view(), name='subcategoria_del'),
    
    path(r'marcas/', MarcaView.as_view(), name='marca_list'),
    path(r'marcas/new', MarcaNew.as_view(), name='marca_new'),
    path(r'marcas/edit/<int:pk>', MarcaEdit.as_view(), name='marca_edit'),
    # path(r'marcas/delete/<int:pk>', MarcaDel.as_view(), name='marca_del'),
    path(r'marcas/inactivar/<int:id>', marca_inactivar, name='marca_inactivar'),
    
    path(r'unidadmedidas/', UnidadMedidaView.as_view(), name='unidadmedida_list'),
    path(r'unidadmedidas/new', UnidadMedidaNew.as_view(), name='unidadmedida_new'),
    path(r'unidadmedidas/edit/<int:pk>', UnidadMedidaEdit.as_view(), name='unidadmedida_edit'),
    path(r'unidadmedidas/inactivar/<int:id>', unidadmedida_inactivar, name='unidadmedida_inactivar'),
    
    path(r'productos/', ProductoView.as_view(), name='producto_list'),
    path(r'productos/new', ProductoNew.as_view(), name='producto_new'),
    path(r'productos/edit/<int:pk>', ProductoEdit.as_view(), name='producto_edit'),
    path(r'productos/inactivar/<int:id>', Producto_inactivar, name='producto_inactivar'),
]

proyecto_Ciudad/urls.py
from django.contrib import admin
from django.urls import re_path, include, path
from apps.cuenta.views import index
from apps.cliente.views import index
from django.contrib.auth.views import LoginView, logout_then_login

urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path('admin/', admin.site.urls),
    re_path(r'^cliente/', include('apps.cliente.urls')),
    re_path(r'^cuenta/', include('apps.cuenta.urls')),
    re_path(r'^tipocuenta/', include('apps.tipocuenta.urls')),
    re_path(r'^usuario/', include('apps.usuario.urls')),
    re_path(r'^ini/', LoginView.as_view(template_name="usuario/index.html"), name="login"),
    re_path(r'^logout/', logout_then_login, name='logout'),
    path('inv/', include(('apps.inv.urls', 'inv'), namespace='inv')),
    path('cmp/', include(('apps.cmp.urls', 'cmp'), namespace='cmp')),
]

apps/cmp/models.py
from django.db import models
from apps.bases.models import ClassModelo
from apps.inv.models import Producto

# Create your models here.
class Proveedor(ClassModelo):
    descripcion=models.CharField(max_length=100, unique=True)
    direccion=models.CharField(max_length=250, null=True, blank=True)
    contacto=models.CharField(max_length=100)
    telefono=models.CharField(max_length=10, null=True, blank=True)
    email=models.CharField(max_length=100, null=True, blank=True)
    
    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion=self.descripcion.upper()
        super(Proveedor, self).save()
        
    class Meta:
        verbose_name_plural="Proveedores"
        

class ComprasEnc(ClassModelo):
    fecha_compra=models.DateField(null=True, blank=True)
    observacion=models.TextField(blank=True, null=True)
    no_factura=models.CharField(max_length=100)
    fecha_factura=models.DateField(null=True, blank=True)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)
    
    proveedor=models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    
    def __str__(self):
        return'{}'.format(self.observacion)
    
    def save(self):
        self.observacion=self.observacion.upper()
        self.total=self.sub_total - ((float(self.sub_total)*(float(self.descuento)))/100)
       
      
        super(ComprasEnc, self).save()
        
    class Meta:
        verbose_name_plural = "Encabezado Compras"
        verbose_name="Encabezado Compra"

class ComprasDet(ClassModelo):
    compra=models.ForeignKey(ComprasEnc, on_delete=models.CASCADE)
    producto=models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad=models.BigIntegerField(default=0)
    precio_prv=models.FloatField(default=0)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)
    costo=models.FloatField(default=0)
    
    def __str__(self):
        return'{}'.fomat(self.producto)
    
    def save(self):
        self.sub_total=float(float(int(self.cantidad))*float(self.precio_prv))
        # self.total=self.sub_total - (self.sub_total*(self.descuento/100))
        # self.total=float(self.sub_total) - ((float(int(self.sub_total))*(float(int(self.descuento)))/100))
        self.total=self.sub_total - ((float(self.sub_total)*(float(self.descuento)))/100)
       
        super(ComprasDet,self).save()
    
    class Meta:
        verbose_name_plural="Detalles Compras"
        verbose_name="Detalle Compra"

apps/cmp/forms.py
from django import forms
from .models import Proveedor, ComprasEnc

class ProveedorForm(forms.ModelForm):
    class Meta:
        model=Proveedor
        
        fields = [
        'descripcion',
        'direccion',
        'contacto',
        'telefono',
        'email',
        'estado'
        ]
        labels={
        'descripcion':'Descripción',
        'direccion': 'Dirección',
        'contacto': 'Contacto',
        'telefono':'Teléfono',
        'email':'Email',
        'estado':'Estado'
            }
        exclude =[
            'um',
            'fm',
            'uc',
            'fc',
        ]
        widgets={
            'descripcion': forms.TextInput,
            # 'estado' : forms.CheckboxSelectMultiple, 
      
           

        }
    def __init__(self, *args, **Kwargs):
        super().__init__(*args, **Kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
           
        self.fields['estado'] = forms.BooleanField()
        
        

class ComprasEncForm(forms.ModelForm):
    fecha_compra=forms.DateInput()
    fecha_factura=forms.DateInput()
    
    class Meta:
        model=ComprasEnc
        fields=['proveedor', 'fecha_compra', 'observacion', 'no_factura', 'fecha_factura', 'sub_total',
                'descuento', 'total']
        
            

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs )
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['fecha_compra'].widget.attrs['readonly']= True
        self.fields['fecha_factura'].widget.attrs['readonly']= True
        self.fields['sub_total'].widget.attrs['readonly']= True
        self.fields['descuento'].widget.attrs['readonly']= True
        self.fields['total'].widget.attrs['readonly']= True


    

apps/cmp/views.py
import datetime
from django.shortcuts import render, redirect
from django.forms.models import BaseModelForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Proveedor, ComprasEnc, ComprasDet
from apps.inv.models import Producto
from .forms import ProveedorForm, ComprasEncForm
from django.urls import reverse_lazy
import json
from django.db.models import Sum

import datetime
# import datetime
# from datetime import datetime, date



# Create your views here.
class ProveedorView(LoginRequiredMixin, generic.ListView):
    model=Proveedor
    template_name="cmp/proveedor_list.html"
    context_object_name="obj"
    login_url="login"
    
class ProveedorNew(LoginRequiredMixin, generic.CreateView):
    model=Proveedor
    template_name="cmp/proveedor_form.html"
    context_object_name="obj"
    form_class=ProveedorForm
    success_url=reverse_lazy('cmp:proveedor_list')
    login_url="login"
    
    def form_valid(self, form):
        form.instance.uc=self.request.user
        return super().form_valid(form)

class ProveedorEdit(LoginRequiredMixin, generic.UpdateView):
    model=Proveedor
    template_name="cmp/proveedor_form.html"
    context_object_name="obj"
    form_class=ProveedorForm
    success_url=reverse_lazy('cmp:proveedor_list')
    login_url="login"
    
    def form_valid(self, form):
        form.instance.um=self.request.user.id
        return super().form_valid(form)

def ProveedorInactivar(request, id):
    template_name="cmp/inactivar_prv.html"
    contexto={}
    prv=Proveedor.objects.filter(pk=id).first()
    
    if not prv:
        return HttpResponse("Proveedor no existe" + str(id))
    
    if request.method=='GET':
        contexto={'obj': prv}
    
    if request.method=='POST':
        prv.estado=False
        prv.save()
        contexto={'obj': 'OK'}
        return HttpResponse("Proveedor Inactivado")
        
     
    return render(request, template_name, contexto)

class ComprasView(LoginRequiredMixin, generic.ListView):
    model=ComprasEnc
    template_name="cmp/compras_list.html"
    context_object_name="obj"
    login_url="login"

def compras(request, compra_id=None):
    template_name="cmp/compras.html"
    prod=Producto.objects.filter(estado=True)
    form_compras={}
    contexto={}
    
    if request.method=='GET':
        form_compras=ComprasEncForm()
        enc = ComprasEnc.objects.filter(pk=compra_id).first()
        
        if enc:
            det = ComprasDet.objects.filter(compra=enc)
            fecha_compra=datetime.date.isoformat(enc.fecha_compra)
            fecha_factura=datetime.date.isoformat(enc.fecha_factura)
   
   
            # fecha_compra=datetime.strptime(enc.fecha_compra, '%Y-%m-%d').strftime('%m/%d/%Y')
            # fecha_factura=datetime.strptime(enc.fecha_factura, '%Y-%m-%d').strftime('%m/%d/%Y')
            e = {
                'fecha_compra': fecha_compra,
                'proveedor':enc.proveedor, 
                'observacion':enc.observacion, 
                'no_factura': enc.no_factura, 
                'fecha_factura': fecha_factura, 
                'sub_total': enc.sub_total,
                'descuento': enc.descuento, 
                'total': enc.total
            }
            form_compras=ComprasEncForm(e)
        else:
            det=None
        contexto={'productos':prod, 'encabezado': enc, 'detalle':det, 'form_enc':form_compras}
        
    if request.method=='POST':
   
        fecha_compra=request.POST.get("fecha_compra")  
        observacion=request.POST.get("observacion")
        no_factura=request.POST.get("no_factura")
        fecha_factura=request.POST.get("fecha_factura")
        proveedor=request.POST.get("proveedor")
        sub_total=0
        descuento=0
        
            
        if not compra_id:
            prov=Proveedor.objects.get(pk=proveedor)

            enc= ComprasEnc(
                fecha_compra=fecha_compra,
                observacion=observacion,
                no_factura=no_factura,
                fecha_factura=fecha_factura,
                proveedor=prov,
                uc=request.user
            )
                
            if enc:
                enc.save()
                compra_id=enc.id
        else:
            enc=ComprasEnc.objects.filter(pk=compra_id).first()
            if enc:
                enc.fecha_compra=fecha_compra
                enc.observacion=observacion
                enc.no_factura=no_factura
                enc.fecha_factura=fecha_factura
                enc.um=request.user.id
                enc.save()

        if not compra_id:
            return redirect("cmp: compras_list")
            
        producto=request.POST.get("id_id_producto")
        cantidad=request.POST.get("id_cantidad_detalle")
        precio=request.POST.get("id_precio_detalle")
        sub_total_detalle=request.POST.get("id_sub_total_detalle")
        descuento_detalle=request.POST.get("id_descuento_detalle")
        total_detalle=request.POST.get("id_total_detalle")
            
        prod=Producto.objects.get(pk=producto)
         
        det=ComprasDet(
            compra=enc,
            producto=prod,
            cantidad=cantidad,
            precio_prv=precio,
            descuento=descuento_detalle,
            costo=0,
            uc=request.user
        )
        if det:
            det.save()
                
            sub_total=ComprasDet.objects.filter(compra=compra_id).aggregate(Sum('sub_total'))
            descuento=ComprasDet.objects.filter(compra=compra_id).aggregate(Sum('descuento'))
            enc.sub_total=sub_total["sub_total__sum"]
            enc.descuento=descuento["descuento__sum"]
            enc.save()
            
        return redirect("cmp:compras_edit", compra_id=compra_id)
            
    return render(request, template_name, contexto)

class CompraDetDelete(LoginRequiredMixin, generic.DeleteView):
    model=ComprasDet
    template_name="cmp/compras_det_del.html"
    context_object_name="obj"
    
    def get_success_url(self):
        compra_id=self.kwargs['compra_id']
        return reverse_lazy('cmp:compras_edit', kwargs={'compra_id': compra_id})
    

templates/cmp/compras.html
{% extends 'base/base.html' %} 
{% block content %}

<form method="post" class="form-inline" id="frmCompras">
  {% csrf_token %}
  <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
    {%if encabezado%}Editar {% else %}Nueva {% endif %}Compra
  </div>
  <div class="dropdown-diviser"></div>
  <div class="row">
    <!-- Inicio en Izquierda -->
    <div class="col-6">
      <!-- Inicio encabezado -->
      <div class="form-group row">
        <label for="" class="col-sm-2 col-form-label">Prov. </label>
        <div class="col-sm-10">{{form_enc.proveedor}}</div>
      </div>
      <div class="row">
        <div class="col-6">
          <div class="form-group">
            <label for="id_fecha_compra">Fecha Compra</label>
            {{form_enc.fecha_compra}}
          </div>
          <div class="form-group">
            <label for="id_descripcion">Descripción</label>
            {{form_enc.observacion}}
          </div>
        </div>
        <div class="col-6">
          <div class="form-group">
            <label for="id_no_factura">No. Factura: </label>
            {{form_enc.no_factura}}
          </div>
          <div class="form-group">
            <label for="id_fecha_factura">Fecha Factura: </label>
            {{form_enc.fecha_factura}}
          </div>
          <div class="row">
            <div class="col">
              <label for="sub_Total">Sub Total: </label>
            </div>
            <div class="col">{{form_enc.sub_total}}</div>
          </div>
          <div class="row">
            <div class="col">
              <label for="decuento">Descuento: </label>
            </div>
            <div class="col">{{form_enc.descuento}}</div>
          </div>
          <div class="row">
            <div class="col">
              <label for="total">Total: </label>
            </div>
            <div class="col">{{form_enc.total}}</div>
          </div>
        </div>
      </div>
    </div>
    <!-- Iniciar Derecha -->
    <div class="col-6">
      <div class="row">
        <div class="col">
          <table
            id="example"
            class="table table-striped table-hover dt-responsive table-sm nowrap tbl-productos"
            style="width: 100%"
          >
            <thead>
              <th>Id</th>
              <th class="all">Descripción</th>
              <th class="all">Precio</th>
              <th class="all">Acciones</th>
            </thead>
            <tbody>
              {% for item in productos %}
              <tr>
                <td>{{item.id}}</td>
                <td>{{item.descripcion}}</td>
                <td>{{item.precio}}</td>
                <td>
                  <button type="button" class="btn btn-warning btn-circle" onclick="selectProducto({{item.id}}, '{{item.descripcion}}', {{item.precio}})">
                    <i class="far fa-hand-pointer"></i>
                  </button>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <div class="form-group row">
        <label for="id_id_producto" class="col-sm-3 col-form-label">Producto</label>
        <div class="col-sm-2">
          <input
            type="text"
            readonly
            class="form-control-plaintext"
            name="id_id_producto"
            id="id_id_producto"
            value=""
            required
          />
        </div>
        <div class="col-sm-2">
          <input
            type="text"
            readonly
            class="form-control-plaintext"
            id="id_descripcion_producto"
            value=""
            required
          />
        </div>
      </div>

      <div class="form-group row">
        <label for="id_cantidad_detalle" class="col-sm-2 col-form-label"
          >Cant:
        </label>
        <div class="col-sm-2">
          <input
            type="number"
            class="form-control"
            name="id_cantidad_detalle"
            id="id_cantidad_detalle"
            value="00"
            required
          />
        </div>
        <label for="id_precio_detalle" class="col-sm-4 col-form-label"
          >Precio:
        </label>
        <div class="col-sm-4">
          <input
            type="number"
            class="form-control"
            name="id_precio_detalle"
            id="id_precio_detalle"
            readonly
            required
          />
        </div>
        <label for="id_descuento_detalle" class="col-sm-3 col-form-label"
          >% Desc:
        </label>
        <div class="col-sm-3">
          <input
            type="number"
            class="form-control"
            name="id_descuento_detalle"
            id="id_descuento_detalle"
            value="00"
            required
          />
        </div>
      </div>

      <div class="form-group row">
        <label for="id_sub_total_detalle" class="col-sm-2 col-form-label"
          >S. Total:
        </label>
        <div class="col-sm-4">
          <input
            type="text"
            readonly
            class="form-control-plaintext"
            name="id_sub_total_detalle"
            id="id_sub_total_detalle"
            value="00"
            required
          />
        </div>
        
        <label for="id_total_detalle" class="col-sm-2 col-form-label"
          >Total:
        </label>
        <div class="col-sm-3">
          <input
            type="number"
            readonly
            class="form-control-plaintext col-sm-10"
            name="id_total_detalle"
            id="id_total_detalle"
            value="00"
            required
          />
        </div>
        <div class="col-sm-3">
          <button
            type="button"
            class="btn btn-sm col-sm-2"
            onclick="clear_detail();">
            <i class="fa fa-minus-circle" aria-hidden="true"></i>
          </button>
        </div>
      </div>
      <!-- Botones -->
      <div class="dropdown-diviser"></div>
      <div class="row">
        <div class="col">
          <button type="submit" class="btn btn-danger">
            <span class="fa fa-save"></span>Guardar
          </button>
          <a href="{% url 'cmp:compras_list' %}" class="btn btn-success"
            ><i class="far fa-hand-point-left"></i>Cancelar</a>
        </div>
      </div>
      <!-- Cierre de botones -->
    </div>
    <!-- Cierre derecha -->
    <!-- Inicio detalle -->
    <div class="row">
      <div class="col">
        <table class="table table-striped table-hover dt-responsive nowrap" style="width: 100%">
          <thead>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Precio</th>
            <th>Sub Total</th>
            <th>Desc.</th>
            <th>Total</th>
            <th class="all">Acciones</th>
          </thead>
          <tbody>
            {%for item in detalle %}
            <tr>
              <td>{{ item.producto}}</td>
              <td>{{ item.cantidad}}</td>
              <td>{{ item.precio_prv}}</td>
              <td>{{ item.sub_total}}</td>
              <td>{{ item.descuento}}</td>
              <td>{{ item.total}}</td>
              <td>
                <button class="btn btn-danger btn-circle"
                onclick="return abrir_modal('{%url 'cmp:compras_del' encabezado.pk item.id%}')">
                 <i class="fas fa-trash-alt"></i>
               </button>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <!-- Fin del detalle -->
  </div>
</form>
{% endblock %} 



{% block js_page%}
    <script>
        //Llamar al plugin del datatables
      
          //  $(`.table`).DataTable({
            $(document).ready(function() {
                //$('#example').DataTable({
                     $(`.table`).DataTable({
                  "language": {
                   // "url": "//cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
                   "decimal": "",
                   "emptyTable": "No hay información",
                   "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                   "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                   "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                   "infoPostFix": "",
                   "thousands": ",",
                   "lengthMenu": "Mostrar _MENU_ Entradas",
                   "loadingRecords": "Cargando...",
                   "processing": "Procesando...",
                   "search": "Buscar:",
                   "zeroRecords": "Sin resultados encontrados",
                   "paginate": {
                       "first": "Primero",
                       "last": "Ultimo",
                       "next": "Siguiente",
                       "previous": "Anterior"
                   }
                  }
                });

                $(
                    "#id_cantidad_detalle, #id_descuento_detalle"
                  ).change(function () {
                    calcular_detalle();
                  });

              /*Validar envío de detalle*/
              $("#frmCompras").submit(function(e){
                if($('#id_total_detalle').val()==0 || $('#id_id_producto').val()==0){
                  e.preventDefault();
                  $.alert({
                    type:'red',
                    title:'',
                    content: 'No ha agregado productos o esta sin cantidades'
                  })
                }
              });



      
              });


              function selectProducto(id, descripcion, valor) {
                $("#id_cantidad_detalle").val(0);
                $("#id_precio_detalle").val(valor);
                $("#id_descuento_detalle").val(0);
                $("#id_sub_total_detalle").val(0);
                $("#id_total_detalle").val(0);
                $("#id_id_producto").val(+id);
                $("#id_descripcion_producto").val(descripcion);
                $("#id_cantidad_detalle").focus();
                $("#id_cantidad_detalle").select();
            
                $(`.table`).DataTable().search('').draw();
                
              }
              
              function calcular_detalle() {
                var cant, prec, desc, stotal, total;
          
                cant = $("#id_cantidad_detalle").val();
                cant = cant === "" ? 0 : +cant;
                cant = cant < 0 ? 0 : cant;
          
                prec = $("#id_precio_detalle").val();
                prec = prec === "" ? 0 : +prec;
                prec = prec < 0 ? 0 : prec;
          
                desc = $("#id_descuento_detalle").val();
                desc = desc === "" ? 0 : +desc;
                desc = desc < 0 ? 0 : desc;
          
                desc = desc > cant * prec ? 0 : desc;
          
                stotal = cant * prec;
                total = stotal - ((stotal*desc)/100);
                //total = stotal - desc;
          
                cant = $("#id_cantidad_detalle").val(cant);
                prec = $("#id_precio_detalle").val(prec);
                desc = $("#id_descuento_detalle").val(desc);
                stotal = $("#id_sub_total_detalle").val(stotal);
                total = $("#id_total_detalle").val(total);

                
              }
          
              function clear_detail() {
                $("#id_cantidad_detalle").val(0);
                $("#id_precio_detalle").val(0);
                $("#id_descuento_detalle").val(0);
                $("#id_sub_total_detalle").val(0);
                $("#id_total_detalle").val(0);
                $("#id_id_producto").val("");
            
                $("#id_descripcion_producto").val("");
                $(`.table`).DataTable().search("").draw();
                $("#id_proveedor").focus();
              }
            
              $("#id_proveedor").focus();
        
    </script>    
{% endblock %}




{% block scripts_local %}
<script>
  $(function () {
    $("#id_fecha_factura, #id_fecha_compra").datetimepicker({
      format: "Y-m-d",
      timepicker: false,
    });
  });
</script>
{% endblock %}

templates/cmp/proveedor_list.html
{% extends 'base/base.html' %}

{% block content %}
<h1>Listado de proveedores</h1>
<div>
    
    <a class="btn btn-primary btn-circle" onclick="return abrir_modal('{% url 'cmp:proveedor_new' %}')" href="#"
    role="button"><i class="fa fa-plus-square"></i>Nuevo</a> 
</div>  

{% comment %} {% url 'inv:categoria_new'%}  {% endcomment %}
{% if not obj%}
<div class="alert alert-info">No hay proveedores</div>
{% else %}
<table id="example" class="table table-striped">
    <thead>
        <tr>
            <td>Id</td>
            <td>Descripción</td>
            <td>Dirección</td>
            <td>Contacto</td>
            <td>Teléfono</td>
            <td>Email</td>
            <td>Estado</td>
            <td class="all">Acciones</td>
        </tr>
    </thead>
    <tbody>
        {% for item in obj %}
        <tr>
            <td>{{ item.id}}</td>
            <td>{{ item.descripcion}}</td>
            <td>{{ item.direccion}}</td>
            <td>{{ item.contacto}}</td>
            <td>{{ item.telefono}}</td>
            <td>{{ item.email}}</td>
            <td>{{ item.estado|yesno:"Activo, Inactivo"}}</td>
            <td>
                <a class="btn btn-warning btn-circle"  onclick="return abrir_modal('{% url 'cmp:proveedor_edit' item.id %}')" href="#"
                role="button"></a>
                <a class="btn btn-danger btn-circle" onclick="return abrir_modal('{% url 'cmp:proveedor_inactivar' item.id %}')"
                role="button"></a>
            </td>
           
        {% endfor %}
        </tr>
    </tbody>
</table>
{% endif %}
{% endblock %}
{% block js_page%}
    <script>
        //Llamar al plugin del datatables
      
          //  $(`.table`).DataTable({
            $(document).ready(function() {
                //$('#example').DataTable({
                     $(`.table`).DataTable({
                  "language": {
                   // "url": "//cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
                   "decimal": "",
                   "emptyTable": "No hay información",
                   "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                   "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                   "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                   "infoPostFix": "",
                   "thousands": ",",
                   "lengthMenu": "Mostrar _MENU_ Entradas",
                   "loadingRecords": "Cargando...",
                   "processing": "Procesando...",
                   "search": "Buscar:",
                   "zeroRecords": "Sin resultados encontrados",
                   "paginate": {
                       "first": "Primero",
                       "last": "Ultimo",
                       "next": "Siguiente",
                       "previous": "Anterior"
                   }
                  }
                });
              });

        
    </script>    
{% endblock %}