apps/inv/urls.py
from django.urls import include, path
from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel,\
    SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, \
        MarcaView, MarcaNew, MarcaEdit, marca_inactivar, \
        UnidadMedidaView, UnidadMedidaNew,  UnidadMedidaEdit, unidadmedida_inactivar, \
            ProductoView,  ProductoNew, ProductoEdit, Producto_inactivar
        # MarcaDel


urlpatterns = [
    # path('admin/', admin.site.urls),
    path(r'categorias/', CategoriaView.as_view(), name='categoria_list'),
    path(r'categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path(r'categorias/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path(r'categorias/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_del'),
    
    path(r'subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path(r'subcategorias/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path(r'subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path(r'subcategorias/delete/<int:pk>', SubCategoriaDel.as_view(), name='subcategoria_del'),
    
    path(r'marcas/', MarcaView.as_view(), name='marca_list'),
    path(r'marcas/new', MarcaNew.as_view(), name='marca_new'),
    path(r'marcas/edit/<int:pk>', MarcaEdit.as_view(), name='marca_edit'),
    # path(r'marcas/delete/<int:pk>', MarcaDel.as_view(), name='marca_del'),
    path(r'marcas/inactivar/<int:id>', marca_inactivar, name='marca_inactivar'),
    
    path(r'unidadmedidas/', UnidadMedidaView.as_view(), name='unidadmedida_list'),
    path(r'unidadmedidas/new', UnidadMedidaNew.as_view(), name='unidadmedida_new'),
    path(r'unidadmedidas/edit/<int:pk>', UnidadMedidaEdit.as_view(), name='unidadmedida_edit'),
    path(r'unidadmedidas/inactivar/<int:id>', unidadmedida_inactivar, name='unidadmedida_inactivar'),
    
    path(r'productos/', ProductoView.as_view(), name='producto_list'),
    path(r'productos/new', ProductoNew.as_view(), name='producto_new'),
    path(r'productos/edit/<int:pk>', ProductoEdit.as_view(), name='producto_edit'),
    path(r'productos/inactivar/<int:id>', Producto_inactivar, name='producto_inactivar'),
]

proyecto_Ciudad/urls.py
from django.contrib import admin
from django.urls import re_path, include, path
from apps.cuenta.views import index
from apps.cliente.views import index
from django.contrib.auth.views import LoginView, logout_then_login

urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path('admin/', admin.site.urls),
    re_path(r'^cliente/', include('apps.cliente.urls')),
    re_path(r'^cuenta/', include('apps.cuenta.urls')),
    re_path(r'^tipocuenta/', include('apps.tipocuenta.urls')),
    re_path(r'^usuario/', include('apps.usuario.urls')),
    re_path(r'^ini/', LoginView.as_view(template_name="usuario/index.html"), name="login"),
    re_path(r'^logout/', logout_then_login, name='logout'),
    path('inv/', include(('apps.inv.urls', 'inv'), namespace='inv')),
    path('cmp/', include(('apps.cmp.urls', 'cmp'), namespace='cmp')),
]

apps/bases/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ClassModelo(models.Model):
    estado=models.BooleanField(default=True)
    fc=models.DateTimeField(auto_now_add=True)
    fm=models.DateTimeField(auto_now=True)
    uc=models.ForeignKey(User, on_delete=models.CASCADE)
    um=models.IntegerField(blank=True, null=True)
    
    class Meta:
        abstract=True

apps/inv/models.py
from django.db import models
from apps.bases.models import ClassModelo

# Create your models here.
class Categoria(ClassModelo):
    descripcion=models.CharField(
        max_length=100,
        help_text='Descripción de Categoría', 
        unique=True
    )
    
    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion=self.descripcion.upper()
        super(Categoria, self).save()
        
    class Meta:
        verbose_name_plural="Categorias"
    
class SubCategoria(ClassModelo):
  
    categoria=models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion=models.CharField(
        max_length=100,
        help_text='Descripción de SubCategoría'
    )
    
    def __str__(self):
        return '{}{}'.format(self.categoria.descripcion, self.descripcion)
    
    def save(self):
        self.descripcion=self.descripcion.upper()
        super(SubCategoria, self).save()
        
    class Meta:
        verbose_name_plural="Sub Categorias"
        unique_together=('categoria', 'descripcion')
        
class Marca(ClassModelo):
    descripcion=models.CharField(
        max_length=100,
        help_text='Descripción de la marca', 
        unique=True
    )
    
    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion=self.descripcion.upper()
        super(Marca, self).save()
        
    class Meta:
        verbose_name_plural="Marca"

class UnidadMedida(ClassModelo):
    descripcion=models.CharField(
        max_length=100,
        help_text='Descripción de la medida', 
        unique=True
    )
    
    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion=self.descripcion.upper()
        super(UnidadMedida, self).save()
        
    class Meta:
        verbose_name_plural="UnidadMedida"
        
        
class Producto(ClassModelo):
    codigo=models.CharField(
        max_length=20,
        unique=True
    )
    codigo_barra=models.CharField(max_length=50)
    descripcion=models.CharField(max_length=200)
    precio=models.FloatField(default=0)
    existencia=models.IntegerField(default=0)
    ultima_compra=models.DateField(null=True, blank=True)
    
    marca=models.ForeignKey(Marca, on_delete=models.CASCADE)
    unidadmedida=models.ForeignKey(UnidadMedida, on_delete=models.CASCADE)
    subcategoria=models.ForeignKey(SubCategoria, on_delete=models.CASCADE)
    
    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion=self.descripcion.upper()
        super(Producto, self).save()
        
    class Meta:
        verbose_name_plural="Producto"
        unique_together=('codigo', 'codigo_barra')
        
    

apps/inv/forms.py
from django import forms
from .models import Categoria, SubCategoria, Marca, UnidadMedida, Producto

class CategoriaForm(forms.ModelForm):
    class Meta:
        model=Categoria
        
        fields = [
            'descripcion',
            'estado'
        ]
        labels={
            'descripcion':'Descripción de la Categoría',
            'estado':'Estado'
        }
        widgets={
            'descripcion': forms.TextInput,
            'estado': forms.CheckboxSelectMultiple,   
        }
    def __init__(self, *args, **Kwargs):
        super().__init__(*args, **Kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
            

class SubCategoriaForm(forms.ModelForm):
    categoria=forms.ModelChoiceField(
        queryset=Categoria.objects.filter(estado=True)
        .order_by('descripcion')
    )
    class Meta:
        model=SubCategoria
        
        fields = [
            'categoria',
            'descripcion',
            'estado'
        ]
        labels={
            'descripcion':'Descripción de Sub Categoría',
            'estado':'Estado'
        }
        widgets={
            'descripcion': forms.TextInput,
            'estado': forms.CheckboxSelectMultiple,   
        }
        
    def __init__(self, *args, **Kwargs):
        super().__init__(*args, **Kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        self.fields['categoria'].empty_label="Seleccione la Categoría"
            

class MarcaForm(forms.ModelForm):
    class Meta:
        model=Marca
        
        fields = [
            'descripcion',
            'estado'
        ]
        labels={
            'descripcion':'Descripción de la marca',
            'estado':'Estado'
        }
        widgets={
            'descripcion': forms.TextInput,
            'estado': forms.CheckboxSelectMultiple,   
        }
    def __init__(self, *args, **Kwargs):
        super().__init__(*args, **Kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class UnidadMedidaForm(forms.ModelForm):
    class Meta:
        model=UnidadMedida
        
        fields = [
            'descripcion',
            'estado'
        ]
        labels={
            'descripcion':'Descripción de la unidad de medida',
            'estado':'Estado'
        }
        widgets={
            'descripcion': forms.TextInput,
            'estado': forms.CheckboxSelectMultiple,   
        }
    def __init__(self, *args, **Kwargs):
        super().__init__(*args, **Kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class ProductoForm(forms.ModelForm):
    class Meta:
        model=Producto
        
        fields = [
            'codigo',
            'codigo_barra',
            'descripcion',
            'estado',
            'precio',
            'existencia',
            'ultima_compra',
            'marca',
            'subcategoria',
            'unidadmedida'
        ]
        labels={
            'codigo':'Código',
            'estado':'Estado'
            }
        exclude =[
            'um',
            'fm',
            'uc',
            'fc',
        ]
        widgets={
            'descripcion': forms.TextInput,
            # 'estado' : forms.CheckboxSelectMultiple, 
      
           

        }
    def __init__(self, *args, **Kwargs):
        super().__init__(*args, **Kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
           
            

        self.fields['ultima_compra'].widget.attrs['readonly']=True
        self.fields['existencia'].widget.attrs['readonly']=True
        self.fields['estado'] = forms.BooleanField()
        
        

    

apps/inv/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Categoria, SubCategoria, Marca, UnidadMedida, Producto
from .forms import CategoriaForm, SubCategoriaForm, MarcaForm, UnidadMedidaForm, ProductoForm
from django.urls import reverse_lazy

# Create your views here.
class CategoriaView(LoginRequiredMixin, generic.ListView):
    model=Categoria
    template_name="inv/Categoria_list.html"
    context_object_name="obj"
    login_url="login"
    
class CategoriaNew(LoginRequiredMixin, generic.CreateView):
    model=Categoria
    template_name="inv/Categoria_form.html"
    context_object_name="obj"
    form_class=CategoriaForm
    success_url=reverse_lazy('inv:categoria_list')
    login_url="login"
    
    def form_valid(self, form):
        form.instance.uc=self.request.user
        return super().form_valid(form)

class CategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model=Categoria
    template_name="inv/Categoria_form.html"
    context_object_name="obj"
    form_class=CategoriaForm
    success_url=reverse_lazy('inv:categoria_list')
    login_url="login"
    
    def form_valid(self, form):
        form.instance.um=self.request.user.id
        return super().form_valid(form)

class CategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model=Categoria
    template_name="inv/categoria_del.html"
    context_object_name="obj"
    success_url=reverse_lazy('inv:categoria_list')
    
class SubCategoriaView(LoginRequiredMixin, generic.ListView):
    model=SubCategoria
    template_name="inv/subcategoria_list.html"
    context_object_name="obj"
    login_url="login"
    
class SubCategoriaNew(LoginRequiredMixin, generic.CreateView):
    model=SubCategoria
    template_name="inv/subcategoria_form.html"
    context_object_name="obj"
    form_class=SubCategoriaForm
    success_url=reverse_lazy('inv:subcategoria_list')
    login_url="login"
    
    def form_valid(self, form):
        form.instance.uc=self.request.user
        return super().form_valid(form)

class SubCategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model=SubCategoria
    template_name="inv/subcategoria_form.html"
    context_object_name="obj"
    form_class=SubCategoriaForm
    success_url=reverse_lazy('inv:subcategoria_list')
    login_url="login"
    
    def form_valid(self, form):
        form.instance.um=self.request.user.id
        return super().form_valid(form)

class SubCategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model=SubCategoria
    template_name="inv/categoria_del.html"
    context_object_name="obj"
    success_url=reverse_lazy('inv:subcategoria_list')
    
class MarcaView(LoginRequiredMixin, generic.ListView):
    model=Marca
    template_name="inv/marca_list.html"
    context_object_name="obj"
    login_url="login"

class MarcaNew(LoginRequiredMixin, generic.CreateView):
    model=Marca
    template_name="inv/marca_form.html"
    context_object_name="obj"
    form_class=MarcaForm
    success_url=reverse_lazy('inv:marca_list')
    login_url="login"
    
    def form_valid(self, form):
        form.instance.uc=self.request.user
        return super().form_valid(form)

class MarcaEdit(LoginRequiredMixin, generic.UpdateView):
    model=Marca
    template_name="inv/marca_form.html"
    context_object_name="obj"
    form_class=MarcaForm
    success_url=reverse_lazy('inv:marca_list')
    login_url="login"
    
    def form_valid(self, form):
        form.instance.um=self.request.user.id
        return super().form_valid(form)

# class MarcaDel(LoginRequiredMixin, generic.DeleteView):
#     model=Marca
#     template_name="inv/categoria_del.html"
#     context_object_name="obj"
#     success_url=reverse_lazy('inv:marca_list')

def marca_inactivar(request, id):
    marca=Marca.objects.filter(pk=id).first()
    contexto={}
    template_name="inv/categoria_del.html"
    if not marca:
        return redirect("inv: marca_list")
    
    if request.method=='GET':
        context={'obj':marca}
    
    if request.method=='POST':
        marca.estado=False
        marca.save()
        return redirect("inv:marca_list")
    
    return render(request, template_name, contexto)


class UnidadMedidaView(LoginRequiredMixin, generic.ListView):
    model=UnidadMedida
    template_name="inv/unidadmedida_list.html"
    context_object_name="obj"
    login_url="login"
    
class UnidadMedidaNew(LoginRequiredMixin, generic.CreateView):
    model=UnidadMedida
    template_name="inv/unidadmedida_form.html"
    context_object_name="obj"
    form_class=UnidadMedidaForm
    success_url=reverse_lazy('inv:unidadmedida_list')
    login_url="login"
    
    def form_valid(self, form):
        form.instance.uc=self.request.user
        return super().form_valid(form)

class UnidadMedidaEdit(LoginRequiredMixin, generic.UpdateView):
    model=UnidadMedida
    template_name="inv/unidadmedida_form.html"
    context_object_name="obj"
    form_class=UnidadMedidaForm
    success_url=reverse_lazy('inv:unidadmedida_list')
    login_url="login"
    
#     def form_valid(self, form):
#         form.instance.um=self.request.user.id
#         return super().form_valid(form)

def unidadmedida_inactivar(request, id):
    unidadmedida=UnidadMedida.objects.filter(pk=id).first()
    contexto={}
    template_name="inv/estado_inactivar.html"
    if not unidadmedida:
        return redirect("inv: unidadmedida_list")
    
    if request.method=='GET':
        context={'obj':unidadmedida}
    
    if request.method=='POST':
        unidadmedida.estado=False
        unidadmedida.save()
        return redirect("inv:unidadmedida_list")
    
    return render(request, template_name, contexto)

class ProductoView(LoginRequiredMixin, generic.ListView):
    model=Producto
    template_name="inv/producto_list.html"
    context_object_name="obj"
    login_url="login"
    
class ProductoView(LoginRequiredMixin, generic.ListView):
    model=Producto
    template_name="inv/producto_list.html"
    context_object_name="obj"
    login_url="login"
    
class ProductoNew(LoginRequiredMixin, generic.CreateView):
    model=Producto
    template_name="inv/producto_form.html"
    context_object_name="obj"
    form_class=ProductoForm
    success_url=reverse_lazy('inv:producto_list')
    login_url="login"
    
    def form_valid(self, form):
        form.instance.uc=self.request.user
        return super().form_valid(form)

class ProductoEdit(LoginRequiredMixin, generic.UpdateView):
    model=Producto
    template_name="inv/producto_form.html"
    context_object_name="obj"
    form_class=ProductoForm
    success_url=reverse_lazy('inv:producto_list')
    login_url="login"
    
    def form_valid(self, form):
        form.instance.um=self.request.user.id
        return super().form_valid(form)

def Producto_inactivar(request, id):
    producto = Producto.objects.filter(pk=id).first()
    contexto={}
    template_name="inv/estado_inactivar.html"
    if not producto:
        return redirect("inv:producto_list")
        
    if request.method=='GET':
        contexto={'obj':producto}

    if request.method=='POST':
        producto.estado=False
        producto.save()
        return redirect("inv:producto_list")
        
    return render(request, template_name, contexto)

templates/inv/categoria_del.html
{% extends 'base/base.html' %}
{% block content%}

<form method='post' class="form-inline">
    {% csrf_token %}
    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
        ¿Desea eliminar {{ obj.descripcion}}?
    </div>
   
    <button class="btn btn-danger" type="submit" class="btn btn-primary";>
        Si, eliminar </button>
    {% comment %} <a class="btn btn-success" href="{% url 'inv:categoria_list' %}"> {% endcomment %}
        <a class="btn btn-success" href="{{request.META.HTTP_REFERER}}"> 
        <span class="fa fa-undo"></span>Cancelar</a>
</form>

{% endblock%}

templates/inv/categoria_form.html
{% extends 'base/base.html' %}

{% block content %}

<form method='post' class="form-inline">
    {% csrf_token %}
    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
        {%if obj%}Editar {% else %}Nueva {% endif %}Categoria
    </div>
    <div class="dropdown-diviser">
    </div>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="descripcion" maxlength="100" class="form-control"
                required id="id_descripcion" placeholder="Descripción" value="{%if obj%}  {{ obj.descripcion}} 
                    {% endif%}">
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_estado">Estado</label>
                <input type="checkbox" id="id_estado" name="estado" value="" checked="True">
            </div>
        </div>
    </div>
    <div class="dropdown-diviser">
    </div>
    <br>
    <div class="row">
        <div class="col">
            <button class="btn btn-danger" type="submit">
                <span class="fa fa-save">
                </span>Guardar</button>
                <a href="{% url 'inv:categoria_list' %}" class="btn btn-success">
                    <span class="fa fa-undo">Cancelar</span>
                </a>
        </div>
    </div>
</form>
{% endblock %}

templates/inv/categoria_list.html
{% extends 'base/base.html' %}

{% block content %}
<h1>Listado de Categoría</h1>
<div>
    <a class="btn btn-primary btn-circle" href="{% url 'inv:categoria_new' %}"
    role="button"><i class="fa fa-plus-square"></i>Nueva</a>
</div>
{% comment %} {% url 'inv:categoria_new'%}  {% endcomment %}
{% if not obj%}
<div class="alert alert-info">No hay categorías</div>
{% else %}
<table class="table table-striped">
    <thead>
        <tr>
            <td>Id</td>
            <td>Descripción</td>
            <td>Estado</td>
            <td>F. Creado</td>
            <td>F. Modif</td>
            <td class="all">Acciones</td>
        </tr>
    </thead>
    <tbody>
        {% for item in obj %}
        <tr>
            <td>{{ item.id}}</td>
            <td>{{ item.descripcion}}</td>
            <td>{{ item.estado|yesno:"Activo, Inactivo"}}</td>
            <td>{{ item.fc|date:"d/m/Y H:i:s"}}</td>
            <td>{{ item.fm|date:"d/m/Y H:i:s"}}</td>
            <td>
                <a class="btn btn-warning btn-circle" href="{% url 'inv:categoria_edit' item.id %}"
                role="button"><i class="fa fa-edit"></i></a>
                <a class="btn btn-danger btn-circle" href="{% url 'inv:categoria_del' item.id %}"
                role="button"><i class="fa fa-trash-alt"></i></a>
            </td>
           
        {% endfor %}
        </tr>
    </tbody>
</table>
{% endif %}
{% endblock %}
{% block js_page%}
    <script>
        //Llamar al plugin del datatables
        $(document).ready(function(){
            $(`.table`).DataTable();
        });
    </script>    
{% endblock %}

templates/inv/marca_form.html
{% extends 'base/base.html' %}

{% block content %}

<form method='post' class="form-inline">
    {% csrf_token %}
    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
        {%if obj%}Editar {% else %}Nueva {% endif %}Marca
    </div>
    <div class="dropdown-diviser">
    </div>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="descripcion" maxlength="100" class="form-control"
                required id="id_descripcion" placeholder="Descripción" value="{%if obj%}  {{ obj.descripcion}} 
                    {% endif%}">
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_estado">Estado</label>
                <input type="checkbox" id="id_estado" name="estado" value="" checked="True">
            </div>
        </div>
    </div>
    <div class="dropdown-diviser">
    </div>
    <br>
    <div class="row">
        <div class="col">
            <button class="btn btn-danger" type="submit">
                <span class="fa fa-save">
                </span>Guardar</button>
                <a href="{% url 'inv:marca_list' %}" class="btn btn-success">
                    <span class="fa fa-undo">Cancelar</span>
                </a>
        </div>
    </div>
</form>
{% endblock %}

templates/inv/marca_list.html
{% extends 'base/base.html' %}

{% block content %}
<h1>Listado de Marcas</h1>
<div>
    <a class="btn btn-primary btn-circle" href="{% url 'inv:marca_new' %}"
    role="button"><i class="fa fa-plus-square"></i>Nueva</a>
</div>
{% comment %} {% url 'inv:categoria_new'%}  {% endcomment %}
{% if not obj%}
<div class="alert alert-info">No hay marcas</div>
{% else %}
<table class="table table-striped">
    <thead>
        <tr>
            <td>Id</td>
            <td>Descripción</td>
            <td>Estado</td>
            <td>F. Creado</td>
            <td>F. Modif</td>
            <td class="all">Acciones</td>
        </tr>
    </thead>
    <tbody>
        {% for item in obj %}
        <tr>
            <td>{{ item.id}}</td>
            <td>{{ item.descripcion}}</td>
            <td>{{ item.estado|yesno:"Activo, Inactivo"}}</td>
            <td>{{ item.fc|date:"d/m/Y H:i:s"}}</td>
            <td>{{ item.fm|date:"d/m/Y H:i:s"}}</td>
            <td>
                <a class="btn btn-warning btn-circle" href="{% url 'inv:marca_edit' item.id %}"
                role="button"><i class="fa fa-edit"></i></a>
                <a class="btn btn-danger btn-circle" href="{% url 'inv:marca_inactivar' item.id %}"
                role="button"><i class="fa fa-toggle-off"></i></a>
            </td>
           
        {% endfor %}
        </tr>
    </tbody>
</table>
{% endif %}
{% endblock %}
{% block js_page%}
    <script>
        //Llamar al plugin del datatables
        $(document).ready(function(){
            $(`.table`).DataTable();
        });
    </script>    
{% endblock %}

templates/inv/subcategoria_list.html
{% extends 'base/base.html' %}

{% block content %}
<h1>Listado de Sub Categorías</h1>
<div>
    <a class="btn btn-primary btn-circle" href="{% url 'inv:subcategoria_new' %}"
    role="button"><i class="fa fa-plus-square"></i>Nueva</a>
</div>
{% comment %} {% url 'inv:categoria_new'%}  {% endcomment %}
{% if not obj%}
<div class="alert alert-info">No hay Sub Categorías</div>
{% else %}
<table class="table table-striped">
    <thead>
        <tr>
            <td>Categoría</td>
            <td>Id</td>
            <td>Descripción</td>
            <td>Estado</td>
            <td>F. Creado</td>
            <td>F. Modif</td>
            <td class="all">Acciones</td>
        </tr>
    </thead>
    <tbody>
        {% for item in obj %}
        <tr>
            <td>{{ item.categoria}}</td>
            <td>{{ item.id}}</td>
            <td>{{ item.descripcion}}</td>
            <td>{{ item.estado|yesno:"Activo, Inactivo"}}</td>
            <td>{{ item.fc|date:"d/m/Y H:i:s"}}</td>
            <td>{{ item.fm|date:"d/m/Y H:i:s"}}</td>
            <td>
                <a class="btn btn-warning btn-circle" href="{% url 'inv:subcategoria_edit' item.id %}"
                role="button"><i class="fa fa-edit"></i></a>
                <a class="btn btn-danger btn-circle" href="{% url 'inv:subcategoria_del' item.id %}"
                role="button"><i class="fa fa-trash-alt"></i></a>
            </td>
           
        {% endfor %}
        </tr>
    </tbody>
</table>
{% endif %}
{% endblock %}
{% block js_page%}
    <script>
        //Llamar al plugin del datatables
        $(document).ready(function(){
            $(`.table`).DataTable();
        });
    </script>    
{% endblock %}

templates/inv/unidadmedida_list.html
{% extends 'base/base.html' %}

{% block content %}
<h1>Listado de unidades de medida</h1>
<div>
    <a class="btn btn-primary btn-circle" href="{% url 'inv:unidadmedida_new' %}"
    role="button"><i class="fa fa-plus-square"></i>Nueva</a>
</div>
{% comment %} {% url 'inv:categoria_new'%}  {% endcomment %}
{% if not obj%}
<div class="alert alert-info">No hay unidades de medida</div>
{% else %}
<table class="table table-striped">
    <thead>
        <tr>
            <td>Id</td>
            <td>Descripción</td>
            <td>Estado</td>
            <td>F. Creado</td>
            <td>F. Modif</td>
            <td class="all">Acciones</td>
        </tr>
    </thead>
    <tbody>
        {% for item in obj %}
        <tr>
            <td>{{ item.id}}</td>
            <td>{{ item.descripcion}}</td>
            <td>{{ item.estado|yesno:"Activo, Inactivo"}}</td>
            <td>{{ item.fc|date:"d/m/Y H:i:s"}}</td>
            <td>{{ item.fm|date:"d/m/Y H:i:s"}}</td>
            <td>
                <a class="btn btn-warning btn-circle" href="{% url 'inv:unidadmedida_edit' item.id %}"
                role="button"><i class="fa fa-edit"></i></a>
                <a class="btn btn-danger btn-circle" href="{% url 'inv:unidadmedida_inactivar' item.id %}"
                role="button"><i class="fa fa-toggle-off"></i></a>
            </td>
           
        {% endfor %}
        </tr>
    </tbody>
</table>
{% endif %}
{% endblock %}
{% block js_page%}
    <script>
        //Llamar al plugin del datatables
        $(document).ready(function(){
            $(`.table`).DataTable();
        });
    </script>    
{% endblock %}